# LiangYong
# 2019/1/12
# 16:16
server:
  port: 37001

spring:
  application:
    name: db-version-consumer

feign:
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:36001/eureka/
  instance:
    instance-id: db-version-consumer
